name: publish

concurrency:
  group: ${{ github.head_ref }}-publish
  cancel-in-progress: true

on:
  push:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ops-kitchen
    - name: Tag docker image for public registry
      run: >
        docker tag ops-kitchen jameskyburz/ops-kitchen &&
        docker tag ops-kitchen jameskyburz/ops-kitchen:$(git describe --tags)
    - name: Login to public docker registry
      run: >
        echo ${{ secrets.DOCKERHUB_PASSWORD }} |
        docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Publish docker images to public registry
      run: >
        docker push jameskyburz/ops-kitchen:latest &&
        docker push jameskyburz/ops-kitchen:$(git describe --tags)
    - name: Tag docker image for github registry
      run: >
        docker tag ops-kitchen docker.pkg.github.com/jameskyburz/ops-kitchen/ops-kitchen &&
        docker tag ops-kitchen docker.pkg.github.com/jameskyburz/ops-kitchen/ops-kitchen:$(git describe --tags)
    - name: Login to github registry
      run: >
        echo ${{ secrets.GITHUB_TOKEN }} |
        docker login docker.pkg.github.com --username JamesKyburz --password-stdin
    - name: Publish docker images to github
      run: >
        docker push docker.pkg.github.com/jameskyburz/ops-kitchen/ops-kitchen:latest &&
        docker push docker.pkg.github.com/jameskyburz/ops-kitchen/ops-kitchen:$(git describe --tags)
